export const metadata = {
  title: "Terms of Service - LearnLM",
};

export default function TermsPage() {
  return (
    <main className="container mx-auto max-w-3xl px-4 py-24">
      <h1 className="text-3xl font-bold tracking-tight mb-6">Terms of Service</h1>
      <p className="text-muted-foreground leading-7 mb-4">
        By using LearnLM, you agree to use the platform for lawful educational purposes and to avoid
        misuse, abuse, or attempts to disrupt service.
      </p>
      <p className="text-muted-foreground leading-7 mb-4">
        Content generated by AI should be reviewed before relying on it for critical decisions. You
        are responsible for how you use generated material.
      </p>
      <p className="text-muted-foreground leading-7">
        These terms may be updated over time. Continued use of the platform constitutes acceptance
        of updated terms.
      </p>
    </main>
  );
}
